### ISSUE TITLE
Add requirements.txt file.

### ISSUE THREAD

**Issue by iprathammishra** [GodfreyCodes/Ai-photo-Editor#2]
It would be better if you'll add the **requirements.txt** (`pip install -r requirements.txt`) file for the packages that you have used in this project.

**Comment by GodfreyCodes** [comment]
> It would be better if you'll add the **requirements.txt** (`pip install -r requirements.txt`) file for the packages that you have used in this project.

I have added it to the repository. Thanks for reminding me.
